/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  BaseResponse,
  CreateSignatoryResponse,
  ErrorResponse,
  SignatorySelfResponse,
  SignatorySignedFormsResponse,
  UpdateSignatoryDto,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const signatoryControllerCreateAccountInternally = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<CreateSignatoryResponse>({
    url: `/api/signatory/create/__internal`,
    method: "POST",
    signal,
  });
};

export const getSignatoryControllerCreateAccountInternallyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signatoryControllerCreateAccountInternally"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
    void
  > = () => {
    return signatoryControllerCreateAccountInternally();
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerCreateAccountInternallyMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>
>;

export type SignatoryControllerCreateAccountInternallyMutationError = ErrorResponse;

export const useSignatoryControllerCreateAccountInternally = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerCreateAccountInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSignatoryControllerCreateAccountInternallyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSelf = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<SignatorySelfResponse>({
    url: `/api/signatory/me`,
    method: "GET",
    signal,
  });
};

export const getSignatoryControllerGetSelfQueryKey = () => {
  return [`/api/signatory/me`] as const;
};

export const getSignatoryControllerGetSelfQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSignatoryControllerGetSelfQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof signatoryControllerGetSelf>>> = ({
    signal,
  }) => signatoryControllerGetSelf(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSelfQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSelf>>
>;
export type SignatoryControllerGetSelfQueryError = ErrorResponse;

export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSelf>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSelf<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSelfQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryControllerGetSelfSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSignatoryControllerGetSelfQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof signatoryControllerGetSelf>>> = ({
    signal,
  }) => signatoryControllerGetSelf(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSelfSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSelf>>
>;
export type SignatoryControllerGetSelfSuspenseQueryError = ErrorResponse;

export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSelfSuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSelf>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof signatoryControllerGetSelf>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSelfSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signatoryControllerUpdateSelf = (updateSignatoryDto: UpdateSignatoryDto) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory/me`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateSignatoryDto,
  });
};

export const getSignatoryControllerUpdateSelfMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
    TError,
    { data: UpdateSignatoryDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
  TError,
  { data: UpdateSignatoryDto },
  TContext
> => {
  const mutationKey = ["signatoryControllerUpdateSelf"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
    { data: UpdateSignatoryDto }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryControllerUpdateSelf(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerUpdateSelfMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>
>;
export type SignatoryControllerUpdateSelfMutationBody = UpdateSignatoryDto;
export type SignatoryControllerUpdateSelfMutationError = ErrorResponse;

export const useSignatoryControllerUpdateSelf = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
      TError,
      { data: UpdateSignatoryDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerUpdateSelf>>,
  TError,
  { data: UpdateSignatoryDto },
  TContext
> => {
  const mutationOptions = getSignatoryControllerUpdateSelfMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const signatoryControllerGetSignedDocumentsBySignatory = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<SignatorySignedFormsResponse>({
    url: `/api/signatory/me/forms`,
    method: "GET",
    signal,
  });
};

export const getSignatoryControllerGetSignedDocumentsBySignatoryQueryKey = () => {
  return [`/api/signatory/me/forms`] as const;
};

export const getSignatoryControllerGetSignedDocumentsBySignatoryQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryControllerGetSignedDocumentsBySignatoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
  > = ({ signal }) => signatoryControllerGetSignedDocumentsBySignatory(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignedDocumentsBySignatoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
>;
export type SignatoryControllerGetSignedDocumentsBySignatoryQueryError = ErrorResponse;

export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
          TError,
          Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignedDocumentsBySignatory<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSignatoryControllerGetSignedDocumentsBySignatoryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSignatoryControllerGetSignedDocumentsBySignatoryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
  > = ({ signal }) => signatoryControllerGetSignedDocumentsBySignatory(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>
>;
export type SignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryError = ErrorResponse;

export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useSignatoryControllerGetSignedDocumentsBySignatorySuspense<
  TData = Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getSignatoryControllerGetSignedDocumentsBySignatorySuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const signatoryControllerGetSignedDocumentsBySignatoryInternally = (
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<SignatorySignedFormsResponse>({
    url: `/api/signatory/me/forms/__internal`,
    method: "POST",
    signal,
  });
};

export const getSignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["signatoryControllerGetSignedDocumentsBySignatoryInternally"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
    void
  > = () => {
    return signatoryControllerGetSignedDocumentsBySignatoryInternally();
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>
>;

export type SignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationError = ErrorResponse;

export const useSignatoryControllerGetSignedDocumentsBySignatoryInternally = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryControllerGetSignedDocumentsBySignatoryInternally>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getSignatoryControllerGetSignedDocumentsBySignatoryInternallyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
