/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface AddFormToGroupDto {
  /** The name of the form to add */
  formName: string;
  /** The ID of the form group */
  groupId: string;
}
