/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { SignatoryEntry } from "./signatoryEntry";
import type { ApproveSignatoryDtoParty } from "./approveSignatoryDtoParty";
import type { ApproveSignatoryDtoValues } from "./approveSignatoryDtoValues";

export interface ApproveSignatoryDto {
  pendingDocumentId: string;
  signatories: SignatoryEntry[];
  party: ApproveSignatoryDtoParty;
  values?: ApproveSignatoryDtoValues;
}
