/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { CreateSignedFormDtoValues } from "./createSignedFormDtoValues";
import type { CreateSignedFormDtoParties } from "./createSignedFormDtoParties";

export interface CreateSignedFormDto {
  formName: string;
  formVersion: number;
  values: CreateSignedFormDtoValues;
  signatories: string[];
  parties: CreateSignedFormDtoParties;
}
