/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { CreatePendingFormDtoValues } from "./createPendingFormDtoValues";
import type { CreatePendingFormDtoParties } from "./createPendingFormDtoParties";

export interface CreatePendingFormDto {
  formName: string;
  formVersion: number;
  values: CreatePendingFormDtoValues;
  parties: CreatePendingFormDtoParties;
}
