/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { EntityWithStatusDtoDisplayName } from "./entityWithStatusDtoDisplayName";
import type { EntityWithStatusDtoType } from "./entityWithStatusDtoType";
import type { EntityWithStatusDtoContactName } from "./entityWithStatusDtoContactName";
import type { EntityWithStatusDtoContactEmail } from "./entityWithStatusDtoContactEmail";
import type { EntityWithStatusDtoContactPhone } from "./entityWithStatusDtoContactPhone";
import type { EntityWithStatusDtoAddress } from "./entityWithStatusDtoAddress";
import type { EntityWithStatusDtoMoaStatus } from "./entityWithStatusDtoMoaStatus";

export interface EntityWithStatusDto {
  id: string;
  /** @nullable */
  display_name: EntityWithStatusDtoDisplayName;
  legal_identifier: string;
  type: EntityWithStatusDtoType;
  contact_name?: EntityWithStatusDtoContactName;
  contact_email?: EntityWithStatusDtoContactEmail;
  contact_phone?: EntityWithStatusDtoContactPhone;
  address?: EntityWithStatusDtoAddress;
  moaStatus: EntityWithStatusDtoMoaStatus;
}
