/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface FieldRegistryEntryDetails {
  id: string;
  name: string;
  label: string;
  preset: string;
  /** @nullable */
  prefiller: string | null;
  /** @nullable */
  tooltip_label: string | null;
  /** @nullable */
  validator: string | null;
}
