/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FieldRegistryEntryDetailsType } from "./fieldRegistryEntryDetailsType";
import type { FieldRegistryEntryDetailsSource } from "./fieldRegistryEntryDetailsSource";
import type { FieldRegistryEntryDetailsValidatorIr } from "./fieldRegistryEntryDetailsValidatorIr";

export interface FieldRegistryEntryDetails {
  id: string;
  name: string;
  label: string;
  type: FieldRegistryEntryDetailsType;
  party: string;
  source: FieldRegistryEntryDetailsSource;
  tag: string;
  shared: boolean;
  preset: string;
  /** @nullable */
  prefiller: string | null;
  /** @nullable */
  tooltip_label: string | null;
  /** @nullable */
  validator: string | null;
  /** @nullable */
  validator_ir?: FieldRegistryEntryDetailsValidatorIr;
  is_phantom: boolean;
}
