/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormFieldType } from "./formFieldType";

export interface FormField {
  field: string;
  type: FormFieldType;
  x: number;
  y: number;
  w: number;
  h: number;
  page: number;
  validator: string;
  transformer: string;
  prefiller: string;
}
