/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type FormMetadataRequiredPartiesItem =
  (typeof FormMetadataRequiredPartiesItem)[keyof typeof FormMetadataRequiredPartiesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormMetadataRequiredPartiesItem = {
  university: "university",
  entity: "entity",
  student: "student",
  "student-guardian": "student-guardian",
} as const;
