/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * @ Modified by: Your name
 * @ Modified time: 2025-12-28 13:56:59
 * OpenAPI spec version: 1.0
 */
import type { Form } from "./form";
import type { FormSubscriber } from "./formSubscriber";

export interface FormMetadata {
  schema_version: number;
  name: string;
  label: string;
  version: number;
  schema: Form;
  subscribers?: FormSubscriber[];
}
