/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormMetadata } from "./formMetadata";
import type { FormDocument } from "./formDocument";

export interface FormLatestResponse {
  success: boolean;
  message: string;
  formMetadata: FormMetadata;
  formDocument: FormDocument;
  formVersion: number;
  documentUrl: string;
}
