/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormSigningPartySignatoryAccount } from "./formSigningPartySignatoryAccount";
import type { FormSigningPartySignatorySource } from "./formSigningPartySignatorySource";

export interface FormSigningParty {
  _id: string;
  order: number;
  signatory_account: FormSigningPartySignatoryAccount;
  signatory_source: FormSigningPartySignatorySource;
  signed: boolean;
}
