/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormField } from "./formField";
import type { FormMetadataEmail } from "./formMetadataEmail";

export interface FormMetadata {
  name: string;
  version: number;
  schema: FormField[];
  subscribers: string[];
  email: FormMetadataEmail;
}
