/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormFieldParty } from "./formFieldParty";
import type { FormFieldSource } from "./formFieldSource";
import type { FormFieldType } from "./formFieldType";

export interface FormField {
  field: string;
  label: string;
  party: FormFieldParty;
  shared: boolean;
  source: FormFieldSource;
  type: FormFieldType;
  tooltip_label: string;
  x: number;
  y: number;
  w: number;
  h: number;
  page: number;
  validator: string;
  prefiller: string;
}
