/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { Form } from "./form";
import type { FormMetadataSubscribers } from "./formMetadataSubscribers";

export interface FormMetadata {
  schema_version: number;
  name: string;
  label: string;
  version: number;
  schema: Form;
  subscribers: FormMetadataSubscribers;
}
