/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export * from "./loginEntityDto";
export * from "./loginSchoolDto";
export * from "./registerEntityDto";
export * from "./registerSchoolDto";
export * from "./requestNewMoaDto";
