/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export * from "./baseResponse";
export * from "./contactDto";
export * from "./countResponse";
export * from "./createCompanyDto";
export * from "./entitiesDto";
export * from "./entitiesResponse";
export * from "./entitiesResponseEntities";
export * from "./entityResponse";
export * from "./entityResponseEntity";
export * from "./errorResponse";
export * from "./loginEntityDto";
export * from "./loginSchoolDto";
export * from "./moaHistoryResponse";
export * from "./moaHistoryResponseHistory";
export * from "./moaRequestResponse";
export * from "./moaRequestResponseRequest";
export * from "./moaRequestsResponse";
export * from "./newCustomMoaRequestResponse";
export * from "./newMoaRequestDto";
export * from "./newStandardMoaRequestDto";
export * from "./newStandardMoaRequestResponse";
export * from "./newTemplatedMoaRequestResponse";
export * from "./profileDto";
export * from "./queryDocResponse";
export * from "./queryDocResponseSignedDocument";
export * from "./queryMoaResponse";
export * from "./queryMoaResponseSignedDocument";
export * from "./registerEntityDto";
export * from "./registerEntityResponse";
export * from "./registerEntityResponseEntity";
export * from "./registerSchoolDto";
export * from "./requestNewMoaDto";
export * from "./requestsResponse";
export * from "./schoolAccountResponse";
export * from "./schoolAccountResponseSchoolAccount";
export * from "./schoolEntitiesControllerGetMyPartnersParams";
export * from "./schoolEntitiesDto";
export * from "./schoolEntitiesResponse";
export * from "./schoolEntityResponse";
export * from "./schoolEntityResponseEntity";
export * from "./schoolResponse";
export * from "./schoolResponseSchool";
export * from "./schoolsControllerListActiveMoasParams";
export * from "./schoolsControllerListCompanyRequestsParams";
export * from "./schoolsResponse";
export * from "./selfSchoolResponse";
export * from "./selfSchoolResponseSchool";
export * from "./selfSchoolResponseSchoolAccount";
