/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { MqJobProgress } from "./mqJobProgress";
import type { PublicMqJobResult } from "./publicMqJobResult";

export interface PublicMqJob {
  id: string;
  type: string;
  status: string;
  progress?: MqJobProgress;
  result?: PublicMqJobResult;
  error?: string;
}
