/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormField } from "./formField";
import type { FormPhantomField } from "./formPhantomField";
import type { RegisterFormSchemaDtoParams } from "./registerFormSchemaDtoParams";
import type { FormSubscriber } from "./formSubscriber";
import type { FormSignatory } from "./formSignatory";
import type { RegisterFormSchemaDtoRequiredPartiesItem } from "./registerFormSchemaDtoRequiredPartiesItem";

export interface RegisterFormSchemaDto {
  name: string;
  label: string;
  schema_version: number;
  schema: FormField[];
  schema_phantoms: FormPhantomField[];
  params: RegisterFormSchemaDtoParams;
  subscribers: FormSubscriber[];
  signatories: FormSignatory[];
  base_document: Blob;
  required_parties: RegisterFormSchemaDtoRequiredPartiesItem[];
}
