/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export type RegisterFormSchemaDtoRequiredPartiesItem =
  (typeof RegisterFormSchemaDtoRequiredPartiesItem)[keyof typeof RegisterFormSchemaDtoRequiredPartiesItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterFormSchemaDtoRequiredPartiesItem = {
  student: "student",
  "student-guardian": "student-guardian",
  university: "university",
  entity: "entity",
} as const;
