/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import type { FormField } from "./formField";
import type { FormContact } from "./formContact";
import type { RegisterFormSchemaDtoRequiredPartiesItem } from "./registerFormSchemaDtoRequiredPartiesItem";

export interface RegisterFormSchemaDto {
  name: string;
  label: string;
  schema_version: number;
  schema: FormField[];
  subscribers: FormContact[];
  signatories: FormContact[];
  base_document: Blob;
  required_parties: RegisterFormSchemaDtoRequiredPartiesItem[];
}
