/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface SchoolEntityDto {
  school_id: string;
  entity_id: string;
  status: string;
}
