/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface SignatoryForm {
  id: string;
  form_label: string;
  form_name: string;
  form_process_id: string;
  form_process_status: string;
  signatory_id: string;
  timestamp: string;
}
