/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */

export interface SignCustomMoaRequestDto {
  school_id: string;
  request_id: string;
  entity_signatory_name: string;
  entity_signatory_title: string;
}
