/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type { ErrorResponse, GetMqJobInternalDto, MqJobResponse } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const mqJobsControllerGetMqJob = (id: string | undefined | null, signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<MqJobResponse>({
    url: `/api/mq-jobs/${id}`,
    method: "GET",
    signal,
  });
};

export const getMqJobsControllerGetMqJobQueryKey = (id?: string | undefined | null) => {
  return [`/api/mq-jobs/${id}`] as const;
};

export const getMqJobsControllerGetMqJobQueryOptions = <
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMqJobsControllerGetMqJobQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>> = ({
    signal,
  }) => mqJobsControllerGetMqJob(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MqJobsControllerGetMqJobQueryResult = NonNullable<
  Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>
>;
export type MqJobsControllerGetMqJobQueryError = ErrorResponse;

export function useMqJobsControllerGetMqJob<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
          TError,
          Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMqJobsControllerGetMqJob<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
          TError,
          Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMqJobsControllerGetMqJob<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMqJobsControllerGetMqJob<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMqJobsControllerGetMqJobQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getMqJobsControllerGetMqJobSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMqJobsControllerGetMqJobQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>> = ({
    signal,
  }) => mqJobsControllerGetMqJob(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MqJobsControllerGetMqJobSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>
>;
export type MqJobsControllerGetMqJobSuspenseQueryError = ErrorResponse;

export function useMqJobsControllerGetMqJobSuspense<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMqJobsControllerGetMqJobSuspense<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMqJobsControllerGetMqJobSuspense<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMqJobsControllerGetMqJobSuspense<
  TData = Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof mqJobsControllerGetMqJob>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMqJobsControllerGetMqJobSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const mqJobsControllerGetMqJobInternally = (
  getMqJobInternalDto: GetMqJobInternalDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<MqJobResponse>({
    url: `/api/mq-jobs/__internal`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: getMqJobInternalDto,
    signal,
  });
};

export const getMqJobsControllerGetMqJobInternallyMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof mqJobsControllerGetMqJobInternally>>,
    TError,
    { data: GetMqJobInternalDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof mqJobsControllerGetMqJobInternally>>,
  TError,
  { data: GetMqJobInternalDto },
  TContext
> => {
  const mutationKey = ["mqJobsControllerGetMqJobInternally"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof mqJobsControllerGetMqJobInternally>>,
    { data: GetMqJobInternalDto }
  > = (props) => {
    const { data } = props ?? {};

    return mqJobsControllerGetMqJobInternally(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type MqJobsControllerGetMqJobInternallyMutationResult = NonNullable<
  Awaited<ReturnType<typeof mqJobsControllerGetMqJobInternally>>
>;
export type MqJobsControllerGetMqJobInternallyMutationBody = GetMqJobInternalDto;
export type MqJobsControllerGetMqJobInternallyMutationError = ErrorResponse;

export const useMqJobsControllerGetMqJobInternally = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof mqJobsControllerGetMqJobInternally>>,
      TError,
      { data: GetMqJobInternalDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof mqJobsControllerGetMqJobInternally>>,
  TError,
  { data: GetMqJobInternalDto },
  TContext
> => {
  const mutationOptions = getMqJobsControllerGetMqJobInternallyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
