/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type { DocsLinkLoginControllerLinkLoginParams } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const docsLinkLoginControllerLinkLogin = (
  params?: DocsLinkLoginControllerLinkLoginParams,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<null>({
    url: `/api/docs/auth/link-login`,
    method: "GET",
    params,
    signal,
  });
};

export const getDocsLinkLoginControllerLinkLoginQueryKey = (
  params?: DocsLinkLoginControllerLinkLoginParams
) => {
  return [`/api/docs/auth/link-login`, ...(params ? [params] : [])] as const;
};

export const getDocsLinkLoginControllerLinkLoginQueryOptions = <
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDocsLinkLoginControllerLinkLoginQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>> = ({
    signal,
  }) => docsLinkLoginControllerLinkLogin(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DocsLinkLoginControllerLinkLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>
>;
export type DocsLinkLoginControllerLinkLoginQueryError = unknown;

export function useDocsLinkLoginControllerLinkLogin<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params: undefined | DocsLinkLoginControllerLinkLoginParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
          TError,
          Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsLinkLoginControllerLinkLogin<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
          TError,
          Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsLinkLoginControllerLinkLogin<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDocsLinkLoginControllerLinkLogin<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDocsLinkLoginControllerLinkLoginQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getDocsLinkLoginControllerLinkLoginSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDocsLinkLoginControllerLinkLoginQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>> = ({
    signal,
  }) => docsLinkLoginControllerLinkLogin(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DocsLinkLoginControllerLinkLoginSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>
>;
export type DocsLinkLoginControllerLinkLoginSuspenseQueryError = unknown;

export function useDocsLinkLoginControllerLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params: undefined | DocsLinkLoginControllerLinkLoginParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsLinkLoginControllerLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDocsLinkLoginControllerLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDocsLinkLoginControllerLinkLoginSuspense<
  TData = Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
  TError = unknown,
>(
  params?: DocsLinkLoginControllerLinkLoginParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof docsLinkLoginControllerLinkLogin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDocsLinkLoginControllerLinkLoginSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
