/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type { BaseResponse, CreateFormGroupDto, ErrorResponse } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const formGroupsControllerGetAllFormGroups = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/form-groups`,
    method: "GET",
    signal,
  });
};

export const getFormGroupsControllerGetAllFormGroupsQueryKey = () => {
  return [`/api/form-groups`] as const;
};

export const getFormGroupsControllerGetAllFormGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFormGroupsControllerGetAllFormGroupsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>
  > = ({ signal }) => formGroupsControllerGetAllFormGroups(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FormGroupsControllerGetAllFormGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>
>;
export type FormGroupsControllerGetAllFormGroupsQueryError = ErrorResponse;

export function useFormGroupsControllerGetAllFormGroups<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
          TError,
          Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetAllFormGroups<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
          TError,
          Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetAllFormGroups<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFormGroupsControllerGetAllFormGroups<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFormGroupsControllerGetAllFormGroupsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFormGroupsControllerGetAllFormGroupsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFormGroupsControllerGetAllFormGroupsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>
  > = ({ signal }) => formGroupsControllerGetAllFormGroups(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FormGroupsControllerGetAllFormGroupsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>
>;
export type FormGroupsControllerGetAllFormGroupsSuspenseQueryError = ErrorResponse;

export function useFormGroupsControllerGetAllFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetAllFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetAllFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFormGroupsControllerGetAllFormGroupsSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
  TError = ErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetAllFormGroups>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFormGroupsControllerGetAllFormGroupsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const formGroupsControllerCreateFormGroup = (
  createFormGroupDto: CreateFormGroupDto,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/form-groups`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createFormGroupDto,
    signal,
  });
};

export const getFormGroupsControllerCreateFormGroupMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof formGroupsControllerCreateFormGroup>>,
    TError,
    { data: CreateFormGroupDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof formGroupsControllerCreateFormGroup>>,
  TError,
  { data: CreateFormGroupDto },
  TContext
> => {
  const mutationKey = ["formGroupsControllerCreateFormGroup"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof formGroupsControllerCreateFormGroup>>,
    { data: CreateFormGroupDto }
  > = (props) => {
    const { data } = props ?? {};

    return formGroupsControllerCreateFormGroup(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FormGroupsControllerCreateFormGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof formGroupsControllerCreateFormGroup>>
>;
export type FormGroupsControllerCreateFormGroupMutationBody = CreateFormGroupDto;
export type FormGroupsControllerCreateFormGroupMutationError = ErrorResponse;

export const useFormGroupsControllerCreateFormGroup = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof formGroupsControllerCreateFormGroup>>,
      TError,
      { data: CreateFormGroupDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof formGroupsControllerCreateFormGroup>>,
  TError,
  { data: CreateFormGroupDto },
  TContext
> => {
  const mutationOptions = getFormGroupsControllerCreateFormGroupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const formGroupsControllerGetFormGroupById = (
  id: string | undefined | null,
  signal?: AbortSignal
) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/form-groups/${id}`,
    method: "GET",
    signal,
  });
};

export const getFormGroupsControllerGetFormGroupByIdQueryKey = (id?: string | undefined | null) => {
  return [`/api/form-groups/${id}`] as const;
};

export const getFormGroupsControllerGetFormGroupByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFormGroupsControllerGetFormGroupByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>
  > = ({ signal }) => formGroupsControllerGetFormGroupById(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FormGroupsControllerGetFormGroupByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>
>;
export type FormGroupsControllerGetFormGroupByIdQueryError = ErrorResponse;

export function useFormGroupsControllerGetFormGroupById<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
          TError,
          Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetFormGroupById<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
          TError,
          Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetFormGroupById<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFormGroupsControllerGetFormGroupById<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFormGroupsControllerGetFormGroupByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFormGroupsControllerGetFormGroupByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFormGroupsControllerGetFormGroupByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>
  > = ({ signal }) => formGroupsControllerGetFormGroupById(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FormGroupsControllerGetFormGroupByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>
>;
export type FormGroupsControllerGetFormGroupByIdSuspenseQueryError = ErrorResponse;

export function useFormGroupsControllerGetFormGroupByIdSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetFormGroupByIdSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFormGroupsControllerGetFormGroupByIdSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFormGroupsControllerGetFormGroupByIdSuspense<
  TData = Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
  TError = ErrorResponse,
>(
  id: string | undefined | null,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof formGroupsControllerGetFormGroupById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFormGroupsControllerGetFormGroupByIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const formGroupsControllerAddFormToGroup = (signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/form-groups/add-form`,
    method: "POST",
    signal,
  });
};

export const getFormGroupsControllerAddFormToGroupMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof formGroupsControllerAddFormToGroup>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof formGroupsControllerAddFormToGroup>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["formGroupsControllerAddFormToGroup"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof formGroupsControllerAddFormToGroup>>,
    void
  > = () => {
    return formGroupsControllerAddFormToGroup();
  };

  return { mutationFn, ...mutationOptions };
};

export type FormGroupsControllerAddFormToGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof formGroupsControllerAddFormToGroup>>
>;

export type FormGroupsControllerAddFormToGroupMutationError = ErrorResponse;

export const useFormGroupsControllerAddFormToGroup = <TError = ErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof formGroupsControllerAddFormToGroup>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof formGroupsControllerAddFormToGroup>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getFormGroupsControllerAddFormToGroupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
