/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { BaseResponse, ErrorResponse, UpdateSignatoryDto } from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const signatoryAccountsControllerUpdateSelf = (updateSignatoryDto: UpdateSignatoryDto) => {
  return preconfiguredAxiosFunction<BaseResponse>({
    url: `/api/signatory-accounts/me`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateSignatoryDto,
  });
};

export const getSignatoryAccountsControllerUpdateSelfMutationOptions = <
  TError = ErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signatoryAccountsControllerUpdateSelf>>,
    TError,
    { data: UpdateSignatoryDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof signatoryAccountsControllerUpdateSelf>>,
  TError,
  { data: UpdateSignatoryDto },
  TContext
> => {
  const mutationKey = ["signatoryAccountsControllerUpdateSelf"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signatoryAccountsControllerUpdateSelf>>,
    { data: UpdateSignatoryDto }
  > = (props) => {
    const { data } = props ?? {};

    return signatoryAccountsControllerUpdateSelf(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SignatoryAccountsControllerUpdateSelfMutationResult = NonNullable<
  Awaited<ReturnType<typeof signatoryAccountsControllerUpdateSelf>>
>;
export type SignatoryAccountsControllerUpdateSelfMutationBody = UpdateSignatoryDto;
export type SignatoryAccountsControllerUpdateSelfMutationError = ErrorResponse;

export const useSignatoryAccountsControllerUpdateSelf = <
  TError = ErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof signatoryAccountsControllerUpdateSelf>>,
      TError,
      { data: UpdateSignatoryDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof signatoryAccountsControllerUpdateSelf>>,
  TError,
  { data: UpdateSignatoryDto },
  TContext
> => {
  const mutationOptions = getSignatoryAccountsControllerUpdateSelfMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
