/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * BetterInternship MOA API
 * The official API of the BetterInternship MOA platform.
 * OpenAPI spec version: 1.0
 */
import { useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  EntityWithStatusResponse,
  ErrorResponse,
  GetMyEntityForSchoolParams,
} from "../../models";

import { preconfiguredAxiosFunction } from "../../../../preconfig.axios";

export const getMyEntityForSchool = (params?: GetMyEntityForSchoolParams, signal?: AbortSignal) => {
  return preconfiguredAxiosFunction<EntityWithStatusResponse>({
    url: `/api/entity/school-entities/self`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetMyEntityForSchoolQueryKey = (params?: GetMyEntityForSchoolParams) => {
  return [`/api/entity/school-entities/self`, ...(params ? [params] : [])] as const;
};

export const getGetMyEntityForSchoolQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyEntityForSchoolQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyEntityForSchool>>> = ({ signal }) =>
    getMyEntityForSchool(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyEntityForSchool>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyEntityForSchoolQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyEntityForSchool>>
>;
export type GetMyEntityForSchoolQueryError = ErrorResponse;

export function useGetMyEntityForSchool<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params: undefined | GetMyEntityForSchoolParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyEntityForSchool>>,
          TError,
          Awaited<ReturnType<typeof getMyEntityForSchool>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyEntityForSchool<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyEntityForSchool>>,
          TError,
          Awaited<ReturnType<typeof getMyEntityForSchool>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyEntityForSchool<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyEntityForSchool<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyEntityForSchoolQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMyEntityForSchoolSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyEntityForSchoolQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyEntityForSchool>>> = ({ signal }) =>
    getMyEntityForSchool(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMyEntityForSchool>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyEntityForSchoolSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyEntityForSchool>>
>;
export type GetMyEntityForSchoolSuspenseQueryError = ErrorResponse;

export function useGetMyEntityForSchoolSuspense<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params: undefined | GetMyEntityForSchoolParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyEntityForSchoolSuspense<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMyEntityForSchoolSuspense<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMyEntityForSchoolSuspense<
  TData = Awaited<ReturnType<typeof getMyEntityForSchool>>,
  TError = ErrorResponse,
>(
  params?: GetMyEntityForSchoolParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMyEntityForSchool>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyEntityForSchoolSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
